runtime: go111

env_variables:
    STRIPE_PUBLISHABLE_KEY: "pk_test_GbRUAk2CAXMVqXvgwLJxnuf0"
    SRIPE_SECRET_KEY: "sk_test_B0T2KXQvtzHqYUvJ3z7orSK8"
    REDIS_ENDPOINT: "redis-15073.c1.us-central1-2.gce.cloud.redislabs.com:15073"
    REDIS_KEY: "0eYhOgM0PwaMKDnksYBdIZ51FXxCxLPf"

handlers:

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
